name: books_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  stack_trace: ^1.10.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^0.13.4
  collection: ^1.18.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          style: normal
    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          style: normal
    - family: OpenSansSemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          style: normal

    - family: OpenSansLight
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          style: normal
